export const translateTable: { [code: string]: { [key: string]: string } } = {
    ru: {
        EDIT: "Редактировать",
        WELLCOME: "Добро пожаловать!",
        POST_EDIT: "Редактировать пост",
        POST_DELETE: "Удалить пост",
        POST_DELETE_TITLE: "Удаление поста",
        POST_DELETE_CONFIRMATION: "Вы уверены, что хотите удалить этот пост? Это действие нельзя будет отменить.",
        POST_NOT_AVAILABLE: "Пост не доступен",
        POST_LOADING: "Загрузка...",
        POST_ATTACHMENTS: "Прикрепленные файлы",
        POST_CREATE: "Создать пост",
        POST_SELECT_SUBSCRIPTIONS: "Выберите подписки",
        POST_TITLE: "Заголовок",
        EDITOR_BOLD: "Жирный",
        EDITOR_ITALIC: "Курсив",
        EDITOR_STRIKETHROUGH: "Зачеркнутый",
        EDITOR_COLOR: "Выбрать цвет текста",
        EDITOR_ADD_IMAGE: "Добавить изображение",
        EDITOR_ADD_VIDEO: "Добавить видео",
        EDITOR_ATTACHMENTS: "Прикрепленные файлы",
        COMMENT_EDIT: "Редактировать",
        COMMENT_DELETE: "Удалить",
        COMMENT_EDIT_TITLE: "Редактировать комментарий",
        COMMENT_PLACEHOLDER: "Напишите комментарий...",
        COMMENT_LOGIN_REQUIRED: "Войдите, чтобы оставить комментарий",
        COMMENT_SEND: "Отправить",
        COMMENTS: "Комментарии",
        COMMENTS_LOADING: "Загрузка комментариев...",
        COMMENTS_EMPTY: "Нет комментариев. Будьте первым, кто оставит комментарий!",
        HOME_TITLE: "Платформа для создателей контента и их подписчиков",
        SIGN_IN: "Войти",
        SIGN_UP: "Зарегистрироваться",
        MAIN_PAGE: "Главная",
        SUBSCRIPTIONS: "Подписки",
        MY_PAGE: "Моя страница",
        PROFILE: "Профиль",
        CUSTOMIZATION: "Оформление",
        PROFILE_SETTINGS: "Настройки профиля",
        USERNAME: "Имя пользователя",
        LOGIN: "Логин",
        PASSWORD: "Пароль",
        CANCEL: "Отмена",
        SAVE: "Сохранить",
        SAVING: "Сохранение...",
        GOAL: "Цель",
        GOAL_OF: "из",
        EDIT_GOAL: "Редактировать цель",
        TARGET_VALUE: "Целевое значение",
        DELETE_CONFIRMATION: "Подтверждение удаления",
        DELETE_GOAL_CONFIRMATION: "Вы уверены, что хотите удалить цель?",
        DELETE: "Удалить",
        CREATE_GOAL: "Создать цель",
        CHANGING_USRNAME: "Изменение имени пользователя",
        CHANGING_LOGIN: "Изменение логина",
        PASSWORD_CHANGE: "Изменение пароля",
        CURRENT_PASSWORD: "Текущий пароль",
        NEW_PASSWORD: "Новый пароль",
        CONFIRM_NEW_PASSWORD: "Подтвердите новый пароль",
        ENTER_CURRENT_PASSWORD: "Введите текущий пароль",
        ENTER_NEW_PASSWORD: "Введите новый пароль",
        PASSWORD_MIN_LENGTH: "Пароль должен содержать не менее 8 символов",
        PASSWORDS_DONT_MATCH: "Пароли не совпадают",
        INCORRECT_CURRENT_PASSWORD: "Неверный текущий пароль",
        PASSWORD_CHANGE_ERROR: "Ошибка при изменении пароля",
        CUSTOMIZATION_SETTINGS: "Настройки оформления",
        THEME: "Тема",
        LANGUAGE: "Язык",
        LIGHT_BLUE: "Светло-голубая",
        DARK_BLUE: "Темно-голубая",
        RUSSIAN: "Русский",
        ENGLISH: "Английский",
        CHINESE: "Китайский",
        SERBIAN: "Сербский",
        SPANISH: "Испанский",
        BECOME_AUTHOR: "Стать автором",
        AUTHOR_PAGE_NAME: "Название страницы автора",
        AUTHOR_PAGE_DESCRIPTION: "Описание страницы автора",
        IMAGE_CROP: "Обрезка изображения",
        UPLOADED_IMAGE: "Загруженное изображение",
        AUTHOR_PAGE_ERROR: "Не удалось открыть страницу автора",
        CREATE_POST: "Создать пост",
        UNSUBSCRIBE: "Отписаться",
        SUBSCRIBE: "Подписаться",
        ADD_DESCRIPTION: "Добавьте описание...",
        NAME_EMPTY_ERROR: "Имя не может быть пустым",
        SUBSCRIPTION_LEVELS: "Уровни подписки",
        NO_POSTS: "Нет постов",
        ADD_SUBSCRIPTION_LEVEL: "Добавить уровень подписки",
        CREATE_NEW_SUBSCRIPTION_LEVEL: "Создать новый уровень подписки",
        TITLE: "Название",
        PRICE: "Цена (₽)",
        DESCRIPTION: "Описание",
        CREATE: "Создать",
        DELETE_SUBSCRIPTION_CONFIRMATION: "Вы уверены, что хотите удалить уровень подписки",
        EDIT_SUBSCRIPTION_LEVEL: "Редактировать уровень подписки",
        SUBSCRIPTION_CHECKOUT: "Оформление подписки",
        CHOOSE_SUBSCRIPTION_PERIOD: "Выбор периода подписки",
        PAYMENT: "Оплата",
        CONFIRMATION: "Подтверждение",
        PRICE_PER_MONTH: "Стоимость: ",
        SUBSCRIPTION_PERIOD: "Период подписки",
        ONE_MONTH: "1 месяц",
        THREE_MONTHS: "3 месяца",
        SIX_MONTHS: "6 месяцев",
        TWELVE_MONTHS: "12 месяцев",
        TOTAL: "Итого:",
        NEXT: "Далее",
        CARD_DETAILS: "Данные карты",
        CARD_NUMBER: "Номер карты",
        CARDHOLDER_NAME: "Имя владельца",
        EXPIRY_DATE: "Срок действия",
        TOTAL_TO_PAY: "Итого к оплате:",
        BACK: "Назад",
        PAY: "Оплатить",
        SUBSCRIPTION_SUCCESS: "Подписка успешно оформлена!",
        SUBSCRIPTION_SUCCESS_MESSAGE: "Вы успешно оформили подписку на уровень",
        FOR: "на",
        MONTH_SINGLE: "месяц",
        MONTH_FEW: "месяца",
        MONTH_MANY: "месяцев",
        AMOUNT_CHARGED: "Сумма списания:",
        CLOSE: "Закрыть",
        CURRENCY: "₽",
        DELETE_IMAGE_CONFIRMATION: "Вы уверены, что хотите удалить изображение?",
        IMAGE_UPLOAD: "Загрузка изображения",
        DRAG_IMAGE_HERE: "Перетащите изображение сюда",
        OR_CLICK_TO_SELECT: "или нажмите для выбора файла",
        FILE_NOT_IMAGE: "Выбранный файл не является изображением",
        HEADER_IMAGE_CROP: "Обрезка изображения шапки",
        ERROR_CROPPING_IMAGE: "Ошибка при обрезке изображения:",
        NO_2D_CONTEXT: "Нет 2d контекста",
        CANVAS_EMPTY: "Холст пуст",
        ADD_PROFILE_HEADER: "Добавить шапку профиля",
        MY_FOLLOWS: "Мои подписки",
        YOU_DONT_HAVE_FOLLOWS: "У вас пока нет подписок",
        CLICK_TO_SEARCH: "Нажмите на иконку поиска, чтобы найти интересных авторов",
        SEARCH_WRITERS: "Поиск авторов...",
        SUBSCRUBERS: "подписчиков",
        NO_WRITERS: "Авторы не найдены",
        TRANSLATING: "Перевести содержимое страницы?"
    },
    en: {
        EDIT: "Edit",
        WELLCOME: "Wellcome!",
        POST_EDIT: "Edit post",
        POST_DELETE: "Delete post",
        POST_DELETE_TITLE: "Delete post",
        POST_DELETE_CONFIRMATION: "Are you sure you want to delete this post? This action cannot be undone.",
        POST_NOT_AVAILABLE: "Post is not available",
        POST_LOADING: "Loading...",
        POST_ATTACHMENTS: "Attachments",
        POST_CREATE: "Create post",
        POST_SELECT_SUBSCRIPTIONS: "Select subscriptions",
        POST_TITLE: "Title",
        EDITOR_BOLD: "Bold",
        EDITOR_ITALIC: "Italic",
        EDITOR_STRIKETHROUGH: "Strikethrough",
        EDITOR_COLOR: "Select text color",
        EDITOR_ADD_IMAGE: "Add image",
        EDITOR_ADD_VIDEO: "Add video",
        EDITOR_ATTACHMENTS: "Attachments",
        COMMENT_EDIT: "Edit",
        COMMENT_DELETE: "Delete",
        COMMENT_EDIT_TITLE: "Edit comment",
        COMMENT_PLACEHOLDER: "Write a comment...",
        COMMENT_LOGIN_REQUIRED: "Login to leave a comment",
        COMMENT_SEND: "Send",
        COMMENTS: "Comments",
        COMMENTS_LOADING: "Loading comments...",
        COMMENTS_EMPTY: "No comments. Be the first to leave a comment!",
        HOME_TITLE: "A platform for content creators and their subscribers",
        SIGN_IN: "Sign in",
        SIGN_UP: "Sign up",
        MAIN_PAGE: "Main page",
        SUBSCRIPTIONS: "Subscriptions",
        MY_PAGE: "My page",
        PROFILE: "Profile",
        CUSTOMIZATION: "Customization",
        PROFILE_SETTINGS: "Profile settings",
        USERNAME: "Username",
        LOGIN: "Login",
        PASSWORD: "Password",
        CANCEL: "Cancel",
        SAVE: "Save",
        SAVING: "Saving...",
        GOAL: "Goal",
        GOAL_OF: "of",
        EDIT_GOAL: "Edit goal",
        TARGET_VALUE: "Target value",
        DELETE_CONFIRMATION: "Delete confirmation",
        DELETE_GOAL_CONFIRMATION: "Are you sure you want to delete this goal?",
        DELETE: "Delete",
        CREATE_GOAL: "Create goal",
        CHANGING_USRNAME: "Change username",
        CHANGING_LOGIN: "Change login",
        PASSWORD_CHANGE: "Change password",
        CURRENT_PASSWORD: "Current password",
        NEW_PASSWORD: "New password",
        CONFIRM_NEW_PASSWORD: "Confirm new password",
        ENTER_CURRENT_PASSWORD: "Enter current password",
        ENTER_NEW_PASSWORD: "Enter new password",
        PASSWORD_MIN_LENGTH: "Password must be at least 8 characters long",
        PASSWORDS_DONT_MATCH: "Passwords don't match",
        INCORRECT_CURRENT_PASSWORD: "Incorrect current password",
        PASSWORD_CHANGE_ERROR: "Error changing password",
        CUSTOMIZATION_SETTINGS: "Customization settings",
        THEME: "Theme",
        LANGUAGE: "Language",
        LIGHT_BLUE: "Light Blue",
        DARK_BLUE: "Dark Blue",
        RUSSIAN: "Russian",
        ENGLISH: "English",
        CHINESE: "Chinese",
        SERBIAN: "Serbian",
        SPANISH: "Spanish",
        BECOME_AUTHOR: "Become an author",
        AUTHOR_PAGE_NAME: "Author page name",
        AUTHOR_PAGE_DESCRIPTION: "Author page description",
        IMAGE_CROP: "Crop image",
        UPLOADED_IMAGE: "Uploaded image",
        AUTHOR_PAGE_ERROR: "Failed to open author page",
        CREATE_POST: "Create post",
        UNSUBSCRIBE: "Unsubscribe",
        SUBSCRIBE: "Subscribe",
        ADD_DESCRIPTION: "Add description...",
        NAME_EMPTY_ERROR: "Name cannot be empty",
        SUBSCRIPTION_LEVELS: "Subscription levels",
        NO_POSTS: "No posts",
        ADD_SUBSCRIPTION_LEVEL: "Add subscription level",
        CREATE_NEW_SUBSCRIPTION_LEVEL: "Create new subscription level",
        TITLE: "Title",
        PRICE: "Price (₽)",
        DESCRIPTION: "Description",
        CREATE: "Create",
        DELETE_SUBSCRIPTION_CONFIRMATION: "Are you sure you want to delete subscription level",
        EDIT_SUBSCRIPTION_LEVEL: "Edit subscription level",
        SUBSCRIPTION_CHECKOUT: "Subscription checkout",
        CHOOSE_SUBSCRIPTION_PERIOD: "Choose subscription period",
        PAYMENT: "Payment",
        CONFIRMATION: "Confirmation",
        PRICE_PER_MONTH: "Price: ",
        SUBSCRIPTION_PERIOD: "Subscription period",
        ONE_MONTH: "1 month",
        THREE_MONTHS: "3 months",
        SIX_MONTHS: "6 months",
        TWELVE_MONTHS: "12 months",
        TOTAL: "Total:",
        NEXT: "Next",
        CARD_DETAILS: "Card details",
        CARD_NUMBER: "Card number",
        CARDHOLDER_NAME: "Cardholder name",
        EXPIRY_DATE: "Expiry date",
        TOTAL_TO_PAY: "Total to pay:",
        BACK: "Back",
        PAY: "Pay",
        SUBSCRIPTION_SUCCESS: "Subscription successfully completed!",
        SUBSCRIPTION_SUCCESS_MESSAGE: "You have successfully subscribed to the level",
        FOR: "for",
        MONTH_SINGLE: "month",
        MONTH_FEW: "months",
        MONTH_MANY: "months",
        AMOUNT_CHARGED: "Amount charged:",
        CLOSE: "Close",
        CURRENCY: "₽",
        DELETE_IMAGE_CONFIRMATION: "Are you sure you want to delete the image?",
        IMAGE_UPLOAD: "Image Upload",
        DRAG_IMAGE_HERE: "Drag image here",
        OR_CLICK_TO_SELECT: "or click to select a file",
        FILE_NOT_IMAGE: "Selected file is not an image",
        HEADER_IMAGE_CROP: "Header Image Crop",
        ERROR_CROPPING_IMAGE: "Error cropping image:",
        NO_2D_CONTEXT: "No 2d context",
        CANVAS_EMPTY: "Canvas is empty",
        ADD_PROFILE_HEADER: "Add profile header",
        MY_FOLLOWS: "My follows",
        YOU_DONT_HAVE_FOLLOWS: "You don`t have subscriptions yet",
        CLICK_TO_SEARCH: "Click search icon to find interesting authors",
        SEARCH_WRITERS: "Search authors...",
        SUBSCRUBERS: "subscribers",
        NO_WRITERS: "Authors not found",
        TRANSLATING: "Translate the page content?"
    },
    zh: {
        EDIT: "编辑",
        WELLCOME: "欢迎！",
        POST_EDIT: "编辑帖子",
        POST_DELETE: "删除帖子",
        POST_DELETE_TITLE: "删除帖子",
        POST_DELETE_CONFIRMATION: "您确定要删除这篇帖子吗？此操作无法撤销。",
        POST_NOT_AVAILABLE: "帖子不可用",
        POST_LOADING: "加载中...",
        POST_ATTACHMENTS: "附件",
        POST_CREATE: "创建帖子",
        POST_SELECT_SUBSCRIPTIONS: "选择订阅",
        POST_TITLE: "标题",
        EDITOR_BOLD: "粗体",
        EDITOR_ITALIC: "斜体",
        EDITOR_STRIKETHROUGH: "删除线",
        EDITOR_COLOR: "选择文字颜色",
        EDITOR_ADD_IMAGE: "添加图片",
        EDITOR_ADD_VIDEO: "添加视频",
        EDITOR_ATTACHMENTS: "附件",
        COMMENT_EDIT: "编辑",
        COMMENT_DELETE: "删除",
        COMMENT_EDIT_TITLE: "编辑评论",
        COMMENT_PLACEHOLDER: "写评论...",
        COMMENT_LOGIN_REQUIRED: "登录后才能发表评论",
        COMMENT_SEND: "发送",
        COMMENTS: "评论",
        COMMENTS_LOADING: "加载评论中...",
        COMMENTS_EMPTY: "暂无评论。成为第一个评论者！",
        HOME_TITLE: "内容创作者与订阅者的平台",
        SIGN_IN: "登录",
        SIGN_UP: "注册",
        MAIN_PAGE: "主页",
        SUBSCRIPTIONS: "订阅",
        MY_PAGE: "我的主页",
        PROFILE: "个人资料",
        CUSTOMIZATION: "自定义",
        PROFILE_SETTINGS: "个人资料设置",
        USERNAME: "用户名",
        LOGIN: "登录",
        PASSWORD: "密码",
        CANCEL: "取消",
        SAVE: "保存",
        SAVING: "保存中...",
        GOAL: "目标",
        GOAL_OF: "共",
        EDIT_GOAL: "编辑目标",
        TARGET_VALUE: "目标值",
        DELETE_CONFIRMATION: "删除确认",
        DELETE_GOAL_CONFIRMATION: "您确定要删除此目标吗？",
        DELETE: "删除",
        CREATE_GOAL: "创建目标",
        CHANGING_USRNAME: "更改用户名",
        CHANGING_LOGIN: "更改登录名",
        PASSWORD_CHANGE: "更改密码",
        CURRENT_PASSWORD: "当前密码",
        NEW_PASSWORD: "新密码",
        CONFIRM_NEW_PASSWORD: "确认新密码",
        ENTER_CURRENT_PASSWORD: "输入当前密码",
        ENTER_NEW_PASSWORD: "输入新密码",
        PASSWORD_MIN_LENGTH: "密码必须至少8个字符",
        PASSWORDS_DONT_MATCH: "密码不匹配",
        INCORRECT_CURRENT_PASSWORD: "当前密码错误",
        PASSWORD_CHANGE_ERROR: "更改密码时出错",
        CUSTOMIZATION_SETTINGS: "自定义设置",
        THEME: "主题",
        LANGUAGE: "语言",
        LIGHT_BLUE: "浅蓝色",
        DARK_BLUE: "深蓝色",
        RUSSIAN: "俄语",
        ENGLISH: "英语",
        CHINESE: "中文",
        SERBIAN: "塞尔维亚语",
        SPANISH: "西班牙语",
        BECOME_AUTHOR: "成为作者",
        AUTHOR_PAGE_NAME: "作者页面名称",
        AUTHOR_PAGE_DESCRIPTION: "作者页面描述",
        IMAGE_CROP: "裁剪图片",
        UPLOADED_IMAGE: "上传的图片",
        AUTHOR_PAGE_ERROR: "打开作者页面失败",
        CREATE_POST: "创建帖子",
        UNSUBSCRIBE: "取消订阅",
        SUBSCRIBE: "订阅",
        ADD_DESCRIPTION: "添加描述...",
        NAME_EMPTY_ERROR: "名称不能为空",
        SUBSCRIPTION_LEVELS: "订阅级别",
        NO_POSTS: "暂无帖子",
        ADD_SUBSCRIPTION_LEVEL: "添加订阅级别",
        CREATE_NEW_SUBSCRIPTION_LEVEL: "创建新的订阅级别",
        TITLE: "标题",
        PRICE: "价格 (₽)",
        DESCRIPTION: "描述",
        CREATE: "创建",
        DELETE_SUBSCRIPTION_CONFIRMATION: "您确定要删除订阅级别",
        EDIT_SUBSCRIPTION_LEVEL: "编辑订阅级别",
        SUBSCRIPTION_CHECKOUT: "订阅结账",
        CHOOSE_SUBSCRIPTION_PERIOD: "选择订阅期限",
        PAYMENT: "支付",
        CONFIRMATION: "确认",
        PRICE_PER_MONTH: "价格：",
        SUBSCRIPTION_PERIOD: "订阅期限",
        ONE_MONTH: "1个月",
        THREE_MONTHS: "3个月",
        SIX_MONTHS: "6个月",
        TWELVE_MONTHS: "12个月",
        TOTAL: "总计：",
        NEXT: "下一步",
        CARD_DETAILS: "银行卡信息",
        CARD_NUMBER: "卡号",
        CARDHOLDER_NAME: "持卡人姓名",
        EXPIRY_DATE: "有效期",
        TOTAL_TO_PAY: "应付总额：",
        BACK: "返回",
        PAY: "支付",
        SUBSCRIPTION_SUCCESS: "订阅成功！",
        SUBSCRIPTION_SUCCESS_MESSAGE: "您已成功订阅级别",
        FOR: "为期",
        MONTH_SINGLE: "个月",
        MONTH_FEW: "个月",
        MONTH_MANY: "个月",
        AMOUNT_CHARGED: "扣款金额：",
        CLOSE: "关闭",
        CURRENCY: "₽",
        DELETE_IMAGE_CONFIRMATION: "您确定要删除这张图片吗？",
        IMAGE_UPLOAD: "图片上传",
        DRAG_IMAGE_HERE: "拖拽图片到这里",
        OR_CLICK_TO_SELECT: "或点击选择文件",
        FILE_NOT_IMAGE: "所选文件不是图片",
        HEADER_IMAGE_CROP: "页眉图片裁剪",
        ERROR_CROPPING_IMAGE: "裁剪图片时出错：",
        NO_2D_CONTEXT: "没有2D上下文",
        CANVAS_EMPTY: "画布为空",
        ADD_PROFILE_HEADER: "添加个人资料页眉",
        MY_FOLLOWS: "我的关注",
        YOU_DONT_HAVE_FOLLOWS: "您还没有订阅任何内容",
        CLICK_TO_SEARCH: "点击搜索图标查找有趣的作者",
        SEARCH_WRITERS: "搜索作者...",
        SUBSCRUBERS: "订阅者",
        NO_WRITERS: "未找到作者",
        TRANSLATING: "翻译页面内容"
    },
    sr: {
        EDIT: "Уреди",
        WELLCOME: "Добродошли!",
        POST_EDIT: "Уреди објаву",
        POST_DELETE: "Обриши објаву",
        POST_DELETE_TITLE: "Обриши објаву",
        POST_DELETE_CONFIRMATION: "Да ли сте сигурни да желите да обришете ову објаву? Ова радња се не може поништити.",
        POST_NOT_AVAILABLE: "Објава није доступна",
        POST_LOADING: "Учитавање...",
        POST_ATTACHMENTS: "Прилози",
        POST_CREATE: "Направи објаву",
        POST_SELECT_SUBSCRIPTIONS: "Изабери претплате",
        POST_TITLE: "Наслов",
        EDITOR_BOLD: "Подебљано",
        EDITOR_ITALIC: "Искошено",
        EDITOR_STRIKETHROUGH: "Прецртано",
        EDITOR_COLOR: "Изабери боју текста",
        EDITOR_ADD_IMAGE: "Додај слику",
        EDITOR_ADD_VIDEO: "Додај видео",
        EDITOR_ATTACHMENTS: "Прилози",
        COMMENT_EDIT: "Уреди",
        COMMENT_DELETE: "Обриши",
        COMMENT_EDIT_TITLE: "Уреди коментар",
        COMMENT_PLACEHOLDER: "Напиши коментар...",
        COMMENT_LOGIN_REQUIRED: "Пријавите се да бисте оставили коментар",
        COMMENT_SEND: "Пошаљи",
        COMMENTS: "Коментари",
        COMMENTS_LOADING: "Учитавање коментара...",
        COMMENTS_EMPTY: "Нема коментара. Будите први који ће оставити коментар!",
        HOME_TITLE: "Платформа за креаторе садржаја и њихове претплатнике",
        SIGN_IN: "Пријави се",
        SIGN_UP: "Региструј се",
        MAIN_PAGE: "Главна страница",
        SUBSCRIPTIONS: "Претплате",
        MY_PAGE: "Моја страница",
        PROFILE: "Профил",
        CUSTOMIZATION: "Прилагођавање",
        PROFILE_SETTINGS: "Подешавања профила",
        USERNAME: "Корисничко име",
        LOGIN: "Пријава",
        PASSWORD: "Лозинка",
        CANCEL: "Откажи",
        SAVE: "Сачувај",
        SAVING: "Чување...",
        GOAL: "Циљ",
        GOAL_OF: "од",
        EDIT_GOAL: "Уреди циљ",
        TARGET_VALUE: "Циљна вредност",
        DELETE_CONFIRMATION: "Потврда брисања",
        DELETE_GOAL_CONFIRMATION: "Да ли сте сигурни да желите да обришете овај циљ?",
        DELETE: "Обриши",
        CREATE_GOAL: "Направи циљ",
        CHANGING_USRNAME: "Промени корисничко име",
        CHANGING_LOGIN: "Промени пријаву",
        PASSWORD_CHANGE: "Промени лозинку",
        CURRENT_PASSWORD: "Тренутна лозинка",
        NEW_PASSWORD: "Нова лозинка",
        CONFIRM_NEW_PASSWORD: "Потврди нову лозинку",
        ENTER_CURRENT_PASSWORD: "Унеси тренутну лозинку",
        ENTER_NEW_PASSWORD: "Унеси нову лозинку",
        PASSWORD_MIN_LENGTH: "Лозинка мора имати најмање 8 карактера",
        PASSWORDS_DONT_MATCH: "Лозинке се не подударају",
        INCORRECT_CURRENT_PASSWORD: "Нетачна тренутна лозинка",
        PASSWORD_CHANGE_ERROR: "Грешка при промени лозинке",
        CUSTOMIZATION_SETTINGS: "Подешавања прилагођавања",
        THEME: "Тема",
        LANGUAGE: "Језик",
        LIGHT_BLUE: "Светло плава",
        DARK_BLUE: "Тамно плава",
        RUSSIAN: "Руски",
        ENGLISH: "Енглески",
        CHINESE: "Кинески",
        SERBIAN: "Српски",
        SPANISH: "Шпански",
        BECOME_AUTHOR: "Постани аутор",
        AUTHOR_PAGE_NAME: "Назив ауторске странице",
        AUTHOR_PAGE_DESCRIPTION: "Опис ауторске странице",
        IMAGE_CROP: "Исеци слику",
        UPLOADED_IMAGE: "Отпремљена слика",
        AUTHOR_PAGE_ERROR: "Отварање ауторске странице није успело",
        CREATE_POST: "Направи објаву",
        UNSUBSCRIBE: "Откажи претплату",
        SUBSCRIBE: "Претплати се",
        ADD_DESCRIPTION: "Додај опис...",
        NAME_EMPTY_ERROR: "Име не може бити празно",
        SUBSCRIPTION_LEVELS: "Нивои претплате",
        NO_POSTS: "Нема објава",
        ADD_SUBSCRIPTION_LEVEL: "Додај ниво претплате",
        CREATE_NEW_SUBSCRIPTION_LEVEL: "Направи нови ниво претплате",
        TITLE: "Наслов",
        PRICE: "Цена (₽)",
        DESCRIPTION: "Опис",
        CREATE: "Направи",
        DELETE_SUBSCRIPTION_CONFIRMATION: "Да ли сте сигурни да желите да обришете ниво претплате",
        EDIT_SUBSCRIPTION_LEVEL: "Уреди ниво претплате",
        SUBSCRIPTION_CHECKOUT: "Плаћање претплате",
        CHOOSE_SUBSCRIPTION_PERIOD: "Изабери период претплате",
        PAYMENT: "Плаћање",
        CONFIRMATION: "Потврда",
        PRICE_PER_MONTH: "Цена: ",
        SUBSCRIPTION_PERIOD: "Период претплате",
        ONE_MONTH: "1 месец",
        THREE_MONTHS: "3 месеца",
        SIX_MONTHS: "6 месеци",
        TWELVE_MONTHS: "12 месеци",
        TOTAL: "Укупно:",
        NEXT: "Даље",
        CARD_DETAILS: "Подаци картице",
        CARD_NUMBER: "Број картице",
        CARDHOLDER_NAME: "Име власника картице",
        EXPIRY_DATE: "Датум истека",
        TOTAL_TO_PAY: "Укупно за плаћање:",
        BACK: "Назад",
        PAY: "Плати",
        SUBSCRIPTION_SUCCESS: "Претплата је успешно завршена!",
        SUBSCRIPTION_SUCCESS_MESSAGE: "Успешно сте се претплатили на ниво",
        FOR: "за",
        MONTH_SINGLE: "месец",
        MONTH_FEW: "месеца",
        MONTH_MANY: "месеци",
        AMOUNT_CHARGED: "Наплаћен износ:",
        CLOSE: "Затвори",
        CURRENCY: "₽",
        DELETE_IMAGE_CONFIRMATION: "Да ли сте сигурни да желите да обришете слику?",
        IMAGE_UPLOAD: "Отпремање слике",
        DRAG_IMAGE_HERE: "Превуци слику овде",
        OR_CLICK_TO_SELECT: "или кликни да изабереш датотеку",
        FILE_NOT_IMAGE: "Изабрана датотека није слика",
        HEADER_IMAGE_CROP: "Исецање слике заглавља",
        ERROR_CROPPING_IMAGE: "Грешка при исецању слике:",
        NO_2D_CONTEXT: "Нема 2D контекста",
        CANVAS_EMPTY: "Платно је празно",
        ADD_PROFILE_HEADER: "Додај заглавље профила",
        MY_FOLLOWS: "Моја праћења",
        YOU_DONT_HAVE_FOLLOWS: "Још увек немате претплате",
        CLICK_TO_SEARCH: "Кликните на икону претраге да пронађете занимљиве ауторе",
        SEARCH_WRITERS: "Претражи ауторе...",
        SUBSCRUBERS: "претплатника",
        NO_WRITERS: "Аутори нису пронађени",
        TRANSLATING: "Превести садржај странице?"
    },
    es: {
        EDIT: "Editar",
        WELLCOME: "¡Bienvenido!",
        POST_EDIT: "Editar publicación",
        POST_DELETE: "Eliminar publicación",
        POST_DELETE_TITLE: "Eliminar publicación",
        POST_DELETE_CONFIRMATION: "¿Estás seguro de que quieres eliminar esta publicación? Esta acción no se puede deshacer.",
        POST_NOT_AVAILABLE: "La publicación no está disponible",
        POST_LOADING: "Cargando...",
        POST_ATTACHMENTS: "Archivos adjuntos",
        POST_CREATE: "Crear publicación",
        POST_SELECT_SUBSCRIPTIONS: "Seleccionar suscripciones",
        POST_TITLE: "Título",
        EDITOR_BOLD: "Negrita",
        EDITOR_ITALIC: "Cursiva",
        EDITOR_STRIKETHROUGH: "Tachado",
        EDITOR_COLOR: "Seleccionar color de texto",
        EDITOR_ADD_IMAGE: "Añadir imagen",
        EDITOR_ADD_VIDEO: "Añadir vídeo",
        EDITOR_ATTACHMENTS: "Archivos adjuntos",
        COMMENT_EDIT: "Editar",
        COMMENT_DELETE: "Eliminar",
        COMMENT_EDIT_TITLE: "Editar comentario",
        COMMENT_PLACEHOLDER: "Escribe un comentario...",
        COMMENT_LOGIN_REQUIRED: "Inicia sesión para dejar un comentario",
        COMMENT_SEND: "Enviar",
        COMMENTS: "Comentarios",
        COMMENTS_LOADING: "Cargando comentarios...",
        COMMENTS_EMPTY: "No hay comentarios. ¡Sé el primero en dejar un comentario!",
        HOME_TITLE: "Una plataforma para creadores de contenido y sus suscriptores",
        SIGN_IN: "Iniciar sesión",
        SIGN_UP: "Registrarse",
        MAIN_PAGE: "Página principal",
        SUBSCRIPTIONS: "Suscripciones",
        MY_PAGE: "Mi página",
        PROFILE: "Perfil",
        CUSTOMIZATION: "Personalización",
        PROFILE_SETTINGS: "Configuración del perfil",
        USERNAME: "Nombre de usuario",
        LOGIN: "Iniciar sesión",
        PASSWORD: "Contraseña",
        CANCEL: "Cancelar",
        SAVE: "Guardar",
        SAVING: "Guardando...",
        GOAL: "Objetivo",
        GOAL_OF: "de",
        EDIT_GOAL: "Editar objetivo",
        TARGET_VALUE: "Valor objetivo",
        DELETE_CONFIRMATION: "Confirmación de eliminación",
        DELETE_GOAL_CONFIRMATION: "¿Estás seguro de que quieres eliminar este objetivo?",
        DELETE: "Eliminar",
        CREATE_GOAL: "Crear objetivo",
        CHANGING_USRNAME: "Cambiar nombre de usuario",
        CHANGING_LOGIN: "Cambiar inicio de sesión",
        PASSWORD_CHANGE: "Cambiar contraseña",
        CURRENT_PASSWORD: "Contraseña actual",
        NEW_PASSWORD: "Nueva contraseña",
        CONFIRM_NEW_PASSWORD: "Confirmar nueva contraseña",
        ENTER_CURRENT_PASSWORD: "Introduce la contraseña actual",
        ENTER_NEW_PASSWORD: "Introduce la nueva contraseña",
        PASSWORD_MIN_LENGTH: "La contraseña debe tener al menos 8 caracteres",
        PASSWORDS_DONT_MATCH: "Las contraseñas no coinciden",
        INCORRECT_CURRENT_PASSWORD: "Contraseña actual incorrecta",
        PASSWORD_CHANGE_ERROR: "Error al cambiar la contraseña",
        CUSTOMIZATION_SETTINGS: "Configuración de personalización",
        THEME: "Tema",
        LANGUAGE: "Idioma",
        LIGHT_BLUE: "Azul claro",
        DARK_BLUE: "Azul oscuro",
        RUSSIAN: "Ruso",
        ENGLISH: "Inglés",
        CHINESE: "Chino",
        SERBIAN: "Serbio",
        SPANISH: "Español",
        BECOME_AUTHOR: "Conviértete en autor",
        AUTHOR_PAGE_NAME: "Nombre de la página del autor",
        AUTHOR_PAGE_DESCRIPTION: "Descripción de la página del autor",
        IMAGE_CROP: "Recortar imagen",
        UPLOADED_IMAGE: "Imagen subida",
        AUTHOR_PAGE_ERROR: "Error al abrir la página del autor",
        CREATE_POST: "Crear publicación",
        UNSUBSCRIBE: "Cancelar suscripción",
        SUBSCRIBE: "Suscribirse",
        ADD_DESCRIPTION: "Añadir descripción...",
        NAME_EMPTY_ERROR: "El nombre no puede estar vacío",
        SUBSCRIPTION_LEVELS: "Niveles de suscripción",
        NO_POSTS: "No hay publicaciones",
        ADD_SUBSCRIPTION_LEVEL: "Añadir nivel de suscripción",
        CREATE_NEW_SUBSCRIPTION_LEVEL: "Crear nuevo nivel de suscripción",
        TITLE: "Título",
        PRICE: "Precio (₽)",
        DESCRIPTION: "Descripción",
        CREATE: "Crear",
        DELETE_SUBSCRIPTION_CONFIRMATION: "¿Estás seguro de que quieres eliminar el nivel de suscripción",
        EDIT_SUBSCRIPTION_LEVEL: "Editar nivel de suscripción",
        SUBSCRIPTION_CHECKOUT: "Pago de suscripción",
        CHOOSE_SUBSCRIPTION_PERIOD: "Elige el período de suscripción",
        PAYMENT: "Pago",
        CONFIRMATION: "Confirmación",
        PRICE_PER_MONTH: "Precio: ",
        SUBSCRIPTION_PERIOD: "Período de suscripción",
        ONE_MONTH: "1 mes",
        THREE_MONTHS: "3 meses",
        SIX_MONTHS: "6 meses",
        TWELVE_MONTHS: "12 meses",
        TOTAL: "Total:",
        NEXT: "Siguiente",
        CARD_DETAILS: "Detalles de la tarjeta",
        CARD_NUMBER: "Número de tarjeta",
        CARDHOLDER_NAME: "Nombre del titular",
        EXPIRY_DATE: "Fecha de vencimiento",
        TOTAL_TO_PAY: "Total a pagar:",
        BACK: "Atrás",
        PAY: "Pagar",
        SUBSCRIPTION_SUCCESS: "¡Suscripción completada con éxito!",
        SUBSCRIPTION_SUCCESS_MESSAGE: "Te has suscrito exitosamente al nivel",
        FOR: "por",
        MONTH_SINGLE: "mes",
        MONTH_FEW: "meses",
        MONTH_MANY: "meses",
        AMOUNT_CHARGED: "Cantidad cobrada:",
        CLOSE: "Cerrar",
        CURRENCY: "₽",
        DELETE_IMAGE_CONFIRMATION: "¿Estás seguro de que quieres eliminar la imagen?",
        IMAGE_UPLOAD: "Subir imagen",
        DRAG_IMAGE_HERE: "Arrastra la imagen aquí",
        OR_CLICK_TO_SELECT: "o haz clic para seleccionar un archivo",
        FILE_NOT_IMAGE: "El archivo seleccionado no es una imagen",
        HEADER_IMAGE_CROP: "Recortar imagen de encabezado",
        ERROR_CROPPING_IMAGE: "Error al recortar la imagen:",
        NO_2D_CONTEXT: "No hay contexto 2D",
        CANVAS_EMPTY: "El lienzo está vacío",
        ADD_PROFILE_HEADER: "Añadir encabezado de perfil",
        MY_FOLLOWS: "Mis seguidos",
        YOU_DONT_HAVE_FOLLOWS: "Aún no tienes suscripciones",
        CLICK_TO_SEARCH: "Haz clic en el icono de búsqueda para encontrar autores interesantes",
        SEARCH_WRITERS: "Buscar autores...",
        SUBSCRUBERS: "suscriptores",
        NO_WRITERS: "No se encontraron autores",
        TRANSLATING: "Traducir el contenido de la página?"
    }
}
